#TWITTER_API_KEY=COyf89fgS9hLpUwtQR8uDRSYo
#TWITTER_API_KEY_SECRET=dUdVYwhXOwgJ3XCIEYC1qkDww81P1ehpBXDHRcqvr3YSuV2baZ
#TWITTER_API_BEARER_TOKEN=AAAAAAAAAAAAAAAAAAAAAIpWjAEAAAAAtWy%2Ff6voba%2BpZQfW3hEX6WX01tM%3DTjULdzmmeYymykVYi650idzmyzLWuETRgS0mzYQolUAAJPoG8g

RULES_URL =https://api.twitter.com/2/tweets/search/stream/rules'
STREAM_URL =https://api.twitter.com/2/tweets/search/stream?tweet.fields=public_metrics&expansions=author_id'